---
# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html
# Used to monitor a metric and stop the training when no improvement is observed

# class LitModel(LightningModule):
#     def validation_step(self, batch, batch_idx):
#         loss = ...
#         self.log("val_loss", loss)
#
# early_stop_callback = EarlyStopping(monitor="val_loss", min_delta=0.00, patience=3, verbose=False, mode="min")
# trainer = Trainer(callbacks=[early_stop_callback])

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: ???   # metric to monitor, must be specified
