# @package _global_

# Order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - callbacks: default
  - loggers: default
  - trainer: default
  - tuner: default
  - debug:
  - finetune:

# Path to the root directory where all the data will be stored
root_dir:

# Working directory where all the logs, etc. will be stored
work_dir:

# Set to True to train the model. Otherwise, the model will not be trained.
train: true

# Set to True to evaluate the model on the test set using the best model weights achieved during training
# Lightning chooses best weights based on the metric specified in checkpoint callback
test: true

# Seed for random number generators in pytorch, numpy, and random
seed: 42

# Path to a checkpoint to load
ckpt_path:

# Set to True to resume weights only from the checkpoint specified in ckpt_path
# It means that only weights will be loaded and optimizer state will be initialized from scratch
resume_weights_only: false
