---
# @package _global_
# Uses only 1% of the training data and 5% of validation/test data

defaults:
  - default
  - _self_

trainer:
  max_epochs: 3
  # Sometimes it’s helpful to only use a fraction of your training, val, test, or predict data (or a set number of batches).
  # For example, you can use 20% of the training set and 1% of the validation set.
  # On larger datasets like Imagenet, this can help you debug or test a few things faster than waiting for a full epoch.
  # * Use only 10% of training data and 1% of val data:
  #   trainer = Trainer(limit_train_batches=0.1, limit_val_batches=0.01)
  # * Use 10 batches of train and 5 batches of val:
  #   trainer = Trainer(limit_train_batches=10, limit_val_batches=5)
  limit_train_batches: 0.01
  limit_val_batches: 0.05
  limit_test_batches: 0.05
  limit_predict_batches:
