name: Code Quality

on:
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Check all files with pre-commit
    timeout-minutes: 30
    steps:
      - name: Checkout code so that it is available to use in the executing runner
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - name: Check all files with pre-commit
        uses: pre-commit/action@v3.0.1
